@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam noteFontSize 11

abstract class Observable {
# observers : Observer[]
+ addObserver (ob : Observer)
+ deleteObserver (ob : Observer)
+ deleteObservers()
+ notifyObservers(arg1 : Object)
}

interface Observer {
+{abstract} update(arg0 : Observable, arg1 : Object)
}

Observable x---right---> "*" Observer : "observers"

@enduml
